version: "3"
services:
  mygowebapp:
    build: .
    image: gowebappimage
    depends_on:
      - redis
    ports:
      - "3000:3000"
    networks:
      - network1
  redis:
    image: redis:latest
    expose:
      - "6379"
    networks:
      - network1

networks:
  network1: