version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - 8080:8080
    
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:latest
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    depends_on:
      - redis

volumes:
  redis-data:
    driver: local
